const ADD_CART_ITEM = "features/Cart/ADD_CART_ITEM";
const REMOVE_CART_ITEM = "features/Cart/REMOVE_CART_ITEM";
const CLEAR_CART_ITEM = "features/Cart/CLEAR_CART_ITEM";
export { ADD_CART_ITEM, CLEAR_CART_ITEM, REMOVE_CART_ITEM };
