const ADD_CART_ITEM = "ADD_CART_ITEM";
const ADD_SUB_TOTAL = "ADD_SUB_TOTAL";
const QTY_COUNTER = "PLUS_QTY";
const CLEAR_CART_ITEM = "CLEAR_CART_ITEM";
const DELETE_CART_ITEM = "DELETE_CART_ITEM";
const CART_LOADING_FALSE = "CART_LOADING_FALSE"
const CART_LOADING_TRUE = "CART_LOADING_TRUE"

export {
  ADD_CART_ITEM,
  ADD_SUB_TOTAL,
  QTY_COUNTER,
  CLEAR_CART_ITEM,
  DELETE_CART_ITEM,
  CART_LOADING_FALSE, 
  CART_LOADING_TRUE
};

