const FETCH_PRODUCT_START = "features/Product/FETCH_PRODUCT_START";
const FETCH_PRODUCT_SUCCESS = "features/Product/FETCH_PRODUCT_SUCCESS";
const FETCH_PRODUCT_ERROR = "features/Product/FETCH_PRODUCT_ERROR";
const SET_CATEGORY = "features/Product/SET_CATEGORY";

export {
  FETCH_PRODUCT_START,
  FETCH_PRODUCT_SUCCESS,
  FETCH_PRODUCT_ERROR,
  SET_CATEGORY,
};
