const SET_PRODUCT = "SET_PRODUCT";
const SET_TAG = "SET_TAG";
const SET_CATEGORIES = "SET_CATEGORIES";
const SET_CATEGORY = "SET_CATEGORY";
const PRODUCT_LOADING_FALSE = "PRODUCT_LOADING_FALSE";
const PRODUCT_LOADING_TRUE = "PRODUCT_LOADING_TRUE";
const SET_TAG_FILTER = "SET_TAG_FILTER";
const SET_PAGE = "SET_PAGE"
const SET_COUNT = "SET_COUNT"

export {
  SET_PRODUCT,
  SET_TAG_FILTER,
  SET_PAGE,
  SET_TAG,
  SET_CATEGORIES,
  SET_CATEGORY,
  PRODUCT_LOADING_FALSE,
  PRODUCT_LOADING_TRUE,
  SET_COUNT
};
