const AUTH_LOADING_TRUE = "AUTH_LOADING_TRUE";
const AUTH_LOADING_FALSE = "AUTH_LOADING_FALSE";
const SET_AUTH_TRUE = "SET_AUTH_TRUE";
const USER_LOGOUT = "USER_LOGOUT";

export { AUTH_LOADING_TRUE, AUTH_LOADING_FALSE, SET_AUTH_TRUE, USER_LOGOUT };
